// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMuT33O0xLILmZP67A5sgLQcJDbjVtb_s',
    appId: '1:621411034968:web:2cf58235d9c96ad33f272d',
    messagingSenderId: '621411034968',
    projectId: 'smart-talk-ai-cc6e2',
    authDomain: 'smart-talk-ai-cc6e2.firebaseapp.com',
    storageBucket: 'smart-talk-ai-cc6e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV0PA9Eqf2P1zLoJFLeV65TFoBwXfoThw',
    appId: '1:621411034968:android:e5c82a5ec767d6a13f272d',
    messagingSenderId: '621411034968',
    projectId: 'smart-talk-ai-cc6e2',
    storageBucket: 'smart-talk-ai-cc6e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrthmSffyVqcxSCFJPweVbaIIgrGDfKu0',
    appId: '1:621411034968:ios:b8d097f13e33d0dd3f272d',
    messagingSenderId: '621411034968',
    projectId: 'smart-talk-ai-cc6e2',
    storageBucket: 'smart-talk-ai-cc6e2.firebasestorage.app',
    iosBundleId: 'com.example.smartTalkAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrthmSffyVqcxSCFJPweVbaIIgrGDfKu0',
    appId: '1:621411034968:ios:b8d097f13e33d0dd3f272d',
    messagingSenderId: '621411034968',
    projectId: 'smart-talk-ai-cc6e2',
    storageBucket: 'smart-talk-ai-cc6e2.firebasestorage.app',
    iosBundleId: 'com.example.smartTalkAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMuT33O0xLILmZP67A5sgLQcJDbjVtb_s',
    appId: '1:621411034968:web:e34646e6d329cb573f272d',
    messagingSenderId: '621411034968',
    projectId: 'smart-talk-ai-cc6e2',
    authDomain: 'smart-talk-ai-cc6e2.firebaseapp.com',
    storageBucket: 'smart-talk-ai-cc6e2.firebasestorage.app',
  );
}
